services:
  discord-bot:
    build: .
    pull_policy: build
    container_name: bogabot
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - data:/data

volumes:
  data: