name: Auto Deploy Bot

on:
  push:
    branches:
      - alexkumar520/auto-deploy
  pull_request:
    branches:
      - alexkumar520/auto-deploy

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: self-hosted
    steps:
        - run: echo "Deploying the bot..."
        - run: |
            nohup ./start_bot.sh &
            disown
        